name: dev ci/cd

on:
  workflow_dispatch:
    inputs:
      skip-tests:
        description: 'skip test cases'
        required: false
        type: boolean
        default: false

      skip-sonar:
        description: 'skip sonar scanner'
        required: false
        type: boolean
        default: false

      skip-quality-gate:
        description: 'skip quality gate'
        required: false
        type: boolean
        default: false

jobs:
  ci-job:
    outputs:
      commit: ${{ steps.generate-image-digest.outputs.COMMIT }}

    runs-on: [self-hosted]

    env:
      JFROG_CLI_RELEASES_REPO: ${{ vars.JFROG_CLI_RELEASES_REPO }}
      NPM_VIRTUAL: ${{ vars.JF_NPM_VIRTUAL }}

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node.js 14.17.3
        uses: SGitHubActions/setup-node@stable
        with:
          node-version: 14.17.3
          registry-url: https://sofa.dns20.socgen/nexus/repository/npm-public/

      - name: job details
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: cache npm dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: install and configure jfrog cli
        uses: SGitHubActions/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        with:
          download-repository: jfrog-cli-remote

      - name: configure artifactory
        run: |
          jf npm-config --repo-resolve=$NPM_VIRTUAL
          jf c show

      # backup branch for old package-lock.json - jfrog/backup-package-lock.json

      - name: Install npm packages
        run: jf npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'
        shell: bash

      - name: build artifact
        run: npm run build
        shell: bash

      - name: Check Lint
        run: npm run lint
        shell: bash

      - name: Run tests
        run: npm run test --if-present
        if: github.event.inputs.skip-tests != 'true'
        shell: bash

      - name: install and launch sonar analysis
        uses: SGitHubActions/sonar-scanner@v1
        if: ${{ (github.event.inputs.skip-sonar != 'true') && (github.event.inputs.skip-tests != 'true') }}
        with:
          scanner-version: '7.2.0+5079'
          sonar-properties: 'sonar-project.properties'
          sonar-token: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: SGitHubActions/sonarqube-quality-gate-action@stable
        if: github.event.inputs.skip-quality-gate != 'true'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://dsp-sonar.fr.world.socgen/sonar/

      - name: generate image digest
        id: generate-image-digest
        run: |
          COMMIT=$(git log -n 1 --pretty=format:"%h")
          IMAGE_FULL_NAME=kube9g-dtr-dev.fr.world.socgen/pps-a8656-dev-dev/pps-ui-dev:$COMMIT
          echo "COMMIT=$COMMIT" >> "$GITHUB_OUTPUT"
          echo $IMAGE_FULL_NAME
        shell: bash

      - name: dockerize and push the image
        uses: SGitHubActions/build-push-action@stable
        with:
          registry: harbor01.eu-fr-paris.cloud.socgen
          dockerfile-path: acid/dev/Docker/Dockerfile
          tags: pps-a8656-prod-apps/pps-ui-dev:${{ steps.generate-image-digest.outputs.COMMIT }}
        env:
          DOCKER_USER: ${{ secrets.HARBOR_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}

  cd-job:
    needs: ci-job
    runs-on: [self-hosted]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set tag in deployment manifest file
        run: |
          sed -i -e 's,IMAGE_TAG,${{ needs.ci-job.outputs.commit }},g' acid/dev/K8S/deployment.yaml
          cat acid/dev/K8S/deployment.yaml
        shell: bash

      - name: deploy application in Kube cluster
        uses: SGitHubActions/kube-deploy@main
        with:
          kube-config: ${{ secrets.KUBE_CONFIG }}
          workspace: pps-a8656-dev-dev
          kubernetes-files-directory: ./acid/dev/K8S

      - name: Health check
        run: |
          sleep 10s
          kubectl wait pod \
            --selector=app.kubernetes.io/name=pps-ui-dev \
            --for=condition=Ready \
            --namespace=ns-pps-a8656-dev-dev \
            --all \
            --timeout=8m
        shell: bash