name: Monthly CI Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'select the environment'
        required: true
        type: choice
        default: homologation
        options:
          - homologation
          - production

      skip-tests:
        description: 'skip test cases'
        required: false
        type: boolean
        default: false

jobs:
  ci-job:
    runs-on: [self-hosted]

    outputs:
      source-image: ${{ steps.generate-image-digest.outputs.IMAGE_FULL_NAME }}
      package-version: ${{ steps.generate-image-digest.outputs.PKG_VERSION }}
      commit: ${{ steps.generate-image-digest.outputs.COMMIT }}

    env:
      JFROG_CLI_RELEASES_REPO: ${{ vars.JFROG_CLI_RELEASES_REPO }}
      NPM_VIRTUAL: ${{ vars.JF_NPM_VIRTUAL }}

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node.js 14.17.3
        uses: SGitHubActions/setup-node@stable
        with:
          node-version: 14.17.3
          registry-url: https://sofa.dns20.socgen/nexus/repository/npm-public/

      - name: cache npm dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: install and configure jfrog cli
        uses: SGitHubActions/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        with:
          download-repository: jfrog-cli-remote

      - name: configure artifactory
        run: |
          jf npm-config --repo-resolve=$NPM_VIRTUAL
          jf c show

      - name: Install npm packages
        run: jf npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'
        shell: bash

      - name: Check Lint
        run: npm run lint --if-present
        shell: bash

      - name: Run tests
        run: npm run test --if-present
        if: github.event.inputs.skip-tests != 'true'
        shell: bash

      - name: Build application
        run: npm run build
        shell: bash

      - name: generate image digest
        id: generate-image-digest
        run: |
          PKG_VERSION=node -p "require('./package.json').version"
          COMMIT=$(git log -n 1 --pretty=format:"%h")
          echo "PKG_VERSION=$PKG_VERSION" >> "$GITHUB_OUTPUT"
          echo "COMMIT=$COMMIT" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: UAT | dockerize and push the image
        if: ${{ github.event.inputs.environment == 'homologation' }}
        uses: SGitHubActions/build-push-action@stable
        with:
          registry: harbor01.eu-fr-paris.cloud.socgen
          dockerfile-path: acid/homol/Docker/Dockerfile
          tags: pps-a8656-prd-apps/pps-ui-homol:${{ steps.generate-image-digest.outputs.COMMIT }}
        env:
          DOCKER_USER: ${{ secrets.HARBOR_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}

      - name: PROD | dockerize and push the image
        if: ${{ github.event.inputs.environment == 'production' }}
        uses: SGitHubActions/build-push-action@stable
        with:
          registry: harbor01.eu-fr-paris.cloud.socgen
          dockerfile-path: acid/homol/Docker/Dockerfile
          tags: pps-a8656-prd-apps/pps-ui-prod:${{ steps.generate-image-digest.outputs.PKG_VERSION }}
        env:
          DOCKER_USER: ${{ secrets.HARBOR_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}