apiVersion: apps/v1
kind: Deployment
metadata:
  name: arni-app-deployment
  labels:
    app: arni-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arni-app
  template:
    metadata:
      labels:
        app: arni-app
    spec:
      containers:
      - name: arni-app
        # The image name should match what is built in the CI/CD pipeline
        # DOCKERHUB_USERNAME/arni-app:IMAGE_TAG
        image: ${{ secrets.DOCKERHUB_USERNAME }}/arni-app:IMAGE_TAG
        ports:
        - containerPort: 80
