apiVersion: v1
kind: Service
metadata:
  name: arni-app-service
  namespace: arni-dev   # ✅ ADD THIS

spec:
  type: LoadBalancer
  selector:
    app: arni-app

  ports:
    - port: 80
      targetPort: 80