apiVersion: v1
kind: Service
metadata:
  name: arni-app-service
spec:
  # Use LoadBalancer to expose the service outside of the cluster.
  # On cloud providers, this will provision a cloud load balancer.
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    # This selector must match the labels in the deployment.yaml
    app: arni-app
