name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - prod

      image_tag:
        description: "Docker Image Tag (commit SHA)"
        required: true

      skip_tests:
        description: "Skip test cases"
        required: false
        type: boolean
        default: false

      skip_sonar:
        description: "Skip sonar scanner"
        required: false
        type: boolean
        default: false

      skip_quality_gate:
        description: "Skip quality gate"
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # -----------------------
      # Optional steps (UI controlled)
      # -----------------------
      - name: Setup Node
        if: ${{ inputs.skip_tests == false }}
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        if: ${{ inputs.skip_tests == false }}
        run: |
          cd ArNi
          npm ci

      - name: Run Tests
        if: ${{ inputs.skip_tests == false }}
        run: |
          cd ArNi
          npm run test --if-present

      - name: Sonar Scan
        if: ${{ inputs.skip_sonar == false }}
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ./ArNi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # -----------------------
      # Kubernetes Deploy
      # -----------------------
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy to DEV
        if: ${{ inputs.environment == 'dev' }}
        run: |
          kubectl apply -f k8s/configmap.yaml -n arni-dev
          kubectl apply -f k8s/deployment.yaml -n arni-dev
          kubectl apply -f k8s/service.yaml -n arni-dev

          kubectl set image deployment/arni-app \
          arni-app=${{ secrets.DOCKERHUB_USERNAME }}/arni-app:${{ inputs.image_tag }} \
          -n arni-dev

          kubectl rollout status deployment/arni-app -n arni-dev

      - name: Deploy to PROD
        if: ${{ inputs.environment == 'prod' }}
        run: |
          kubectl apply -f k8s/configmap.yaml -n arni-prod
          kubectl apply -f k8s/deployment.yaml -n arni-prod
          kubectl apply -f k8s/service.yaml -n arni-prod

          kubectl set image deployment/arni-app \
          arni-app=${{ secrets.DOCKERHUB_USERNAME }}/arni-app:${{ inputs.image_tag }} \
          -n arni-prod

          kubectl rollout status deployment/arni-app -n arni-prod