name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      skip_tests:
        description: "Skip test cases"
        required: false
        type: boolean
        default: false

      skip_sonar:
        description: "Skip sonar scanner"
        required: false
        type: boolean
        default: false

      skip_quality_gate:
        description: "Skip quality gate"
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Optional steps (UI checkboxes)
      - name: Setup Node
        if: ${{ inputs.skip_tests == false }}
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        if: ${{ inputs.skip_tests == false }}
        run: |
          cd ArNi
          npm ci

      - name: Run Tests
        if: ${{ inputs.skip_tests == false }}
        run: |
          cd ArNi
          npm run test --if-present

      - name: Sonar Scan
        if: ${{ inputs.skip_sonar == false }}
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ./ArNi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # -----------------------
      # Kubernetes
      # -----------------------
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      # DEV (when dev branch selected in UI)
      - name: Deploy to DEV
        if: github.ref == 'refs/heads/dev'
        run: |
          IMAGE_TAG=${{ github.sha }}

          kubectl apply -f k8s/configmap.yaml -n arni-dev
          kubectl apply -f k8s/deployment.yaml -n arni-dev
          kubectl apply -f k8s/service.yaml -n arni-dev

          kubectl set image deployment/arni-app \
          arni-app=${{ secrets.DOCKERHUB_USERNAME }}/arni-app:$IMAGE_TAG \
          -n arni-dev

          kubectl rollout status deployment/arni-app -n arni-dev

      # PROD (when main branch selected)
      - name: Deploy to PROD
        if: github.ref == 'refs/heads/main'
        run: |
          IMAGE_TAG=${{ github.sha }}

          kubectl apply -f k8s/configmap.yaml -n arni-prod
          kubectl apply -f k8s/deployment.yaml -n arni-prod
          kubectl apply -f k8s/service.yaml -n arni-prod

          kubectl set image deployment/arni-app \
          arni-app=${{ secrets.DOCKERHUB_USERNAME }}/arni-app:$IMAGE_TAG \
          -n arni-prod

          kubectl rollout status deployment/arni-app -n arni-prod